ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'SQL13' WITH (PRIMARY_ROLE(READ_ONLY_ROUTING_LIST = ((N'SQL12',N'SQL11'))))
GO
USE [master]
GO
ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'SQL12' WITH (SECONDARY_ROLE(READ_ONLY_ROUTING_URL = N'TCP://SQL12:1433'))
GO
ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'SQL12' WITH (PRIMARY_ROLE(READ_ONLY_ROUTING_LIST = (N'SQL11',N'SQL13')))
GO
USE [master]
GO
ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'SQL11' WITH (SECONDARY_ROLE(READ_ONLY_ROUTING_URL = N'TCP://SQL11:1433'))
GO
ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'SQL11' WITH (PRIMARY_ROLE(READ_ONLY_ROUTING_LIST = (N'SQL12',N'SQL13')))
GO


USE [master]
GO
ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'mars_lab01\sqllab01' WITH (SECONDARY_ROLE(READ_ONLY_ROUTING_URL = N'TCP://mars_lab01:1435'))
GO
ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'earth_lab02\sqllab02' WITH (SECONDARY_ROLE(READ_ONLY_ROUTING_URL = N'TCP://earth_lab02:1435'))
GO
ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'jupiter_lab03\sqllab03' WITH (SECONDARY_ROLE(READ_ONLY_ROUTING_URL = N'TCP://jupiter_lab03:1435'))
GO
ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'mars_lab01\sqllab01' WITH (PRIMARY_ROLE(READ_ONLY_ROUTING_LIST = (N'earth_lab02\sqllab02',N'jupiter_lab03\sqllab03')))
GO
USE [master]
GO
ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'earth_lab02\sqllab02' WITH (PRIMARY_ROLE(READ_ONLY_ROUTING_LIST = (N'mars_lab01\sqllab01',N'jupiter_lab03\sqllab03')))
GO
USE [master]
GO
ALTER AVAILABILITY GROUP [ag_pluto]
MODIFY REPLICA ON N'jupiter_lab03\sqllab03' WITH (PRIMARY_ROLE(READ_ONLY_ROUTING_LIST = (N'mars_lab01\sqllab01',N'earth_lab02\sqllab02')))
GO

--test

sqlcmd -S ag_pluto_list -K readonly -E -d andromeda